services:
  redis:
    image: redis:7.4-alpine
    container_name: redis-inmemory
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

  jbombserverbrowser:
    build: .
    container_name: jbombserverbrowser
    ports:
      - "8081:8081"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis